function camera
    
    global CAMERA MISC FIG CONFIG RESULT UI

    panel = uipanel( ...
        'title', 'camera' ...
      , 'units', 'pixels' ...
      , 'parent', FIG.main ...
      , 'fontSize', 8 ...
      , 'position', [ MISC.padding ( 2 * MISC.padding + MISC.controls ) ( 360 + 2 * MISC.padding ) ( MISC.controls + MISC.padding ) ] ...
    );

    
    % connect / disconnect
    UI.camera.connect = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'string', 'connect' ...
      , 'position', [ MISC.padding/2 ( MISC.padding/2 + MISC.controls/2 ) 80 20 ] ...
      , 'callback', @connectOrDisconnect ...
    );

    function connectOrDisconnect( element, varargin )
        if isempty( CAMERA.handle )
            if CAMERA.connect()
                set( element, 'string', 'disconnect' );
            end
        else
            if CAMERA.disconnect()
                set( element, 'string', 'connect' );
            end
        end
    end


    % align
    UI.camera.align = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 80 ) ( MISC.padding/2 + MISC.controls/2 ) 100 20 ] ...
      , 'string', 'align camera' ...
      , 'callback', @CAMERA.align ...
    );


    % hdr
    UI.camera.hdr = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2*3 + 80 + 100 ) ( MISC.padding/2 + MISC.controls/2 ) 100 20 ] ...
      , 'string', 'capture HDR' ...
      , 'callback', @( varargin )( CAMERA.hdr() ) ...
    );


    % display
    group = uibuttongroup( ...
        'parent', panel ...
      , 'units', 'pixels' ...
      , 'position', [ ( MISC.padding/2 - 10 ) ( MISC.padding/2 + 17 ) 1 1 ] ...
      , 'title', 'display:' ...
      , 'selectionChangeFcn', @liveOrLastHDR ...
    );
    
    UI.camera.display.live = uicontrol( ...
        'style', 'togglebutton' ...
      , 'parent', group ...
      , 'units', 'pixels' ...
      , 'position', [ 60 -2 40 20 ] ...
      , 'value', 1 ...
      , 'string', 'live' ...
      , 'tag', 'image' ...
    );

    UI.camera.display.hdr = uicontrol( ...
        'style', 'togglebutton' ...
      , 'parent', group ...
      , 'units', 'pixels' ...
      , 'position', [ 110 -2 70 20 ] ...
      , 'value', 0 ...
      , 'string', 'last HDR' ...
      , 'tag', 'hdr' ...
    );

    function liveOrLastHDR( ~, eventData )
        CONFIG.display = get( eventData.NewValue, 'tag' );
        RESULT.display();
    end


    % exposure
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 180 ) ( MISC.padding/2 - 2 ) 60 20 ] ...
      , 'string', 'exposure:' ...
    );

    UI.camera.exposure.slider = uicontrol( ...
        'style', 'slider' ...
      , 'parent', panel ...
      , 'value', length( CAMERA.exposureRange ) ...
      , 'min', 1 ...
      , 'max', length( CAMERA.exposureRange ) ...
      , 'sliderStep', [ 1 10 ] / ( length( CAMERA.exposureRange ) - 1 ) ...
      , 'position', [ ( MISC.padding + 235 ) ( MISC.padding/2 + 2 ) 85 16 ] ...
      , 'enable', 'on' ...
      , 'callback', @setExposure ...
    );

    UI.camera.exposure.text = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2*3 + 320 ) ( MISC.padding/2 + 1 ) 40 18 ] ...
      , 'string', '-' ...
      , 'enable', 'off' ...
    );

    function setExposure( element, varargin )
        index = round( get( element, 'value' ) );
        CAMERA.setExposure( CAMERA.exposureRange( index ) );
    end

end