function target

    global MISC FIG UTIL TARGET UI

    panel = uipanel( ...
        'title', 'target' ...
      , 'units', 'pixels' ...
      , 'parent', FIG.main ...
      , 'fontSize', 8 ...
      , 'position', [ ( 4 * MISC.padding + 580 ) ( 2 * MISC.padding + MISC.controls ) ( 280 + MISC.padding ) ( MISC.controls + MISC.padding ) ] ...
    );


    % shift x
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 5 ) ( MISC.padding/2 + MISC.controls/2 - 2 ) 40 20 ] ...
      , 'string', 'shift x:' ...
    );
    UI.target.shift.x = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 40 ) ( MISC.padding/2 + MISC.controls/2 + 1 ) 40 18 ] ...
      , 'string', '0' ...
      , 'min', -1000 ...
      , 'max', 1000 ...
      , 'keyPressFcn', @( element, key )( UTIL.step( element, key, 1, 'transform.shift.x', @TARGET.transform ) ) ...
      , 'callback', @( element, ~ )( UTIL.fill( element, 'transform.shift.x', @TARGET.transform ) ) ...
    );

    % shift y
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 5 ) ( MISC.padding/2 - 2 ) 40 20 ] ...
      , 'string', 'shift y:' ...
    );
    UI.target.shift.y = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 40 ) ( MISC.padding/2 + 1 ) 40 18 ] ...
      , 'string', '0' ...
      , 'min', -1000 ...
      , 'max', 1000 ...
      , 'keyPressFcn', @( element, key )( UTIL.step( element, key, 1, 'transform.shift.y', @TARGET.transform ) ) ...
      , 'callback', @( element, ~ )( UTIL.fill( element, 'transform.shift.y', @TARGET.transform ) ) ...
    );


    % scale x
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 105 ) ( MISC.padding/2 + MISC.controls/2 - 2 ) 40 20 ] ...
      , 'string', 'scale x:' ...
    );
    UI.target.scale.x = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 140 ) ( MISC.padding/2 + MISC.controls/2 + 1 ) 40 18 ] ...
      , 'string', '1' ...
      , 'min', 0.01 ...
      , 'max', 10 ...
      , 'keyPressFcn', @( element, key )( UTIL.step( element, key, .01, 'transform.scale.x', @TARGET.transform ) ) ...
      , 'callback', @( element, ~ )( UTIL.fill( element, 'transform.scale.x', @TARGET.transform ) ) ...
    );

    % scale y
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 105 ) ( MISC.padding/2 - 2 ) 40 20 ] ...
      , 'string', 'scale y:' ...
    );
    UI.target.scale.y = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 140 ) ( MISC.padding/2 + 1 ) 40 18 ] ...
      , 'string', '1' ...
      , 'min', 0.01 ...
      , 'max', 10 ...
      , 'keyPressFcn', @( element, key )( UTIL.step( element, key, .01, 'transform.scale.y', @TARGET.transform ) ) ...
      , 'callback', @( element, ~ )( UTIL.fill( element, 'transform.scale.y', @TARGET.transform ) ) ...
    );


    % angle
    uicontrol( ...
        'style', 'text' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 195 ) ( MISC.padding/2 + MISC.controls/2 - 2 ) 40 20 ] ...
      , 'string', 'angle:' ...
    );
    UI.target.angle = uicontrol( ...
        'style', 'edit' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding + 230 ) ( MISC.padding/2 + MISC.controls/2 + 1 ) 40 18 ] ...
      , 'string', '0' ...
      , 'min', -360 ...
      , 'max', 360 ...
      , 'keyPressFcn', @( element, key )( UTIL.step( element, key, .5, 'transform.angle', @TARGET.transform ) ) ...
      , 'callback', @( element, ~ )( UTIL.fill( element, 'transform.angle', @TARGET.transform ) ) ...
    );


    % invert
    UI.target.invert = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'position', [ ( MISC.padding/2 + 210 ) ( MISC.padding/2 ) 70 20 ] ...
      , 'string', 'invert' ...
      , 'callback', @TARGET.invert ...
    );
end