function controller

    global MISC FIG UTIL CONTROLLER CONFIG UI

    panel = uipanel( ...
        'title', 'controller' ...
      , 'units', 'pixels' ...
      , 'parent', FIG.main ...
      , 'fontSize', 8 ...
      , 'position', [ ( 2 * MISC.padding + 100 ) ( MISC.padding ) ( 160 + MISC.padding ) ( MISC.controls + MISC.padding ) ] ...
    );

    % reset
    UI.controller.auto = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'string', 'reset' ...
      , 'position', [ ( MISC.padding/2 ) ( MISC.padding/2 + MISC.controls/2 ) 60 20 ]...
      , 'callback', @CONTROLLER.reset ...
    );

    % auto iterate
    UI.controller.auto = uicontrol( ...
        'style', 'togglebutton' ...
      , 'parent', panel ...
      , 'string', 'auto iterate' ...
      , 'value', CONFIG.autoIterate ...
      , 'position', [ ( MISC.padding + 60 ) ( MISC.padding/2 + MISC.controls/2 ) 90 20 ]...
      , 'callback', @( element, ~ )( UTIL.toggle( element, 'autoIterate', @CONTROLLER.autoIterate ) ) ...
    );

    % iteration++
    UI.controller.iterate = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'string', 'iteration++' ...
      , 'position', [ ( MISC.padding/2 ) ( MISC.padding/2 ) 100 20 ]...
      , 'callback', @CONTROLLER.iterate ...
    );




end