function slm

    global SLM CONFIG MISC UTIL FIG UI

    panel = uipanel( ...
        'title', 'slm' ...
      , 'units', 'pixels' ...
      , 'parent', FIG.main ...
      , 'fontSize', 8 ...
      , 'position', [ ( MISC.padding ) ( MISC.padding ) ( 80 + MISC.padding ) ( MISC.controls + MISC.padding ) ] ...
    );

    % calibrate
    UI.slm.calibrate = uicontrol( ...
        'style', 'pushbutton' ...
      , 'parent', panel ...
      , 'position', [ MISC.padding/2 ( MISC.padding/2 + MISC.controls/2 ) 80 20 ] ...
      , 'string', 'calibrate' ...
      , 'callback', @SLM.calibrate ...
    );

    % blank
    UI.slm.blank = uicontrol( ...
        'style', 'togglebutton' ...
      , 'parent', panel ...
      , 'value', CONFIG.blankSLM ...
      , 'position', [ MISC.padding/2 ( MISC.padding/2 ) 60 20 ] ...
      , 'string', 'blank' ...
      , 'callback', @( element, ~ )( UTIL.toggle( element, 'blankSLM', @SLM.update ) ) ...
    );
end